return {
	bullet=
	{
		[1]=
		{
			id = 1,
			desc = "星星普通子弹",
			speed = 20,
			bullet_num = 1,
			audio_name = "battle_snow",
			shouji_pre = "xx_shouji",
			bullet_prefab_name = "BulletPrefab_xing_01",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 5,
		},
		[2]=
		{
			id = 2,
			desc = "弓箭普通子弹",
			speed = 20,
			bullet_num = 3,
			audio_name = "battle_arrow",
			shouji_pre = "YX_zidna_jian_shouji_02",
			bullet_prefab_name = "BulletPrefab16",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[3]=
		{
			id = 3,
			desc = "瓶子跑普通子弹（废弃）",
			speed = 25,
			bullet_num = 1,
			audio_name = "battle_laser",
			bullet_prefab_name = "BulletPrefab13",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[4]=
		{
			id = 4,
			desc = "毒液普通子弹",
			speed = 20,
			bullet_num = 1,
			audio_name = "battle_syringe",
			shouji_pre = "CS_duye_shouji_01",
			bullet_prefab_name = "BulletPrefab15",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[5]=
		{
			id = 5,
			desc = "回血炮台子弹",
			speed = 25,
			bullet_num = 3,
			audio_name = "battle_syringe",
			shouji_pre = "SJ_aixin",
			bullet_prefab_name = "BulletPrefabHF",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[6]=
		{
			id = 6,
			desc = "加速炮台子弹",
			speed = 10,
			bullet_num = 1,
			audio_name = "battle_syringe",
			shouji_pre = "SJ_aixin",
			bullet_prefab_name = "BulletPrefabJS",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[7]=
		{
			id = 7,
			speed = 10,
			bullet_num = 1,
			audio_name = "battle_syringe",
			shouji_pre = "SJ_aixin",
			bullet_prefab_name = "BulletPrefab_huixuan",
			move = "CircleMoveWithRadiusUP",
			hit_start = "IsHitSomeOne",
			hit_effect = "PenetrateHit",
			hit_type = "SectorShoot",
			bullet_life_time = 30,
		},
		[8]=
		{
			id = 8,
			desc = "瓶子跑技能",
			speed = 16,
			bullet_num = 1,
			attr = "BombHit#3",
			audio_name = "battle_laser",
			shouji_pre = "YX_zidan_huo_shouji",
			bullet_prefab_name = "YX_zidna_huo",
			move = "LineMove",
			hit_start = "IsReachTarget",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 10,
		},
		[9]=
		{
			id = 9,
			desc = "金币怪子弹",
			speed = 25,
			bullet_num = 10,
			audio_name = "battle_laser",
			bullet_prefab_name = "BulletPrefab13",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[10]=
		{
			id = 10,
			desc = "回旋镖子弹",
			speed = 10,
			bullet_num = 1,
			audio_name = "battle_hero_feibiao",
			shouji_pre = "SJ_aixin",
			bullet_prefab_name = "YX_zidan_huixuan_01",
			move = "WhirlyMove",
			hit_start = "IsHitSome",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "SectorShoot",
			bullet_life_time = 30,
		},
		[11]=
		{
			id = 11,
			desc = "回旋镖技能",
			speed = 10,
			bullet_num = 1,
			audio_name = "battle_syringe",
			shouji_pre = "YX_zidan_hx_shouji_01",
			bullet_prefab_name = "BulletPrefab_huixuan_super",
			move = "CircleMoveWithRadiusUP",
			hit_start = "IsHitSomeOne",
			hit_effect = "PenetrateHit",
			hit_type = "SectorShoot",
			bullet_life_time = 30,
		},
		[12]=
		{
			id = 12,
			desc = "毒花普通",
			speed = 5,
			bullet_num = 1,
			damage = 50,
			attr = "Poisoning#100",
			audio_name = "battle_snow",
			shouji_pre = "xx_shouji",
			bullet_prefab_name = "du_kuosan",
			move = "BossWaveMove",
			hit_start = "HitOnSelfPos",
			hit_effect = "PenetrateBombHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[13]=
		{
			id = 13,
			desc = "金币怪子弹",
			speed = 25,
			bullet_num = 3,
			audio_name = "battle_laser",
			bullet_prefab_name = "BulletPrefab13",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "GQShoot",
			bullet_life_time = 2,
		},
		[14]=
		{
			id = 14,
			desc = "毒花技能",
			speed = 5,
			bullet_num = 1,
			damage = 50,
			attr = "Poisoning#100",
			audio_name = "battle_snow",
			shouji_pre = "xx_shouji",
			bullet_prefab_name = "BulletPrefab_duhua_super",
			move = "GQMoveWithSelf",
			hit_start = "IsHitSome",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "SectorShoot",
			bullet_life_time = 6,
		},
		[15]=
		{
			id = 15,
			desc = "毒弹普攻",
			speed = {25,5},
			bullet_num = {1,1},
			damage = {50,5},
			attr = {"poisoning#5","Poisoning#100"},
			audio_name = "battle_syringe",
			shouji_pre = {"duye_shouji","duye_shouji"},
			bullet_prefab_name = {"BulletPrefab6","BulletPrefab_duhua_super"},
			move = {"LineMove","BossWaveMove"},
			hit_start = {"IsHitSomeOne","IsHitSome"},
			hit_effect = {"SampleHit","ExtraPenetrateHit"},
			hit_type = {"SectorShoot","SectorShoot"},
			bullet_life_time = 6,
		},
		[16]=
		{
			id = 16,
			desc = "毒弹技能",
			speed = {25,5},
			bullet_num = {3,1},
			damage = {50,5},
			attr = {"poisoning#5","Poisoning#100"},
			audio_name = "battle_syringe",
			shouji_pre = {"duye_shouji","duye_shouji"},
			bullet_prefab_name = {"BulletPrefab6","BulletPrefab_duhua_super"},
			move = {"LineMove","BossWaveMove"},
			hit_start = {"IsHitSomeOne","IsHitSome"},
			hit_effect = {"SampleHit","ExtraPenetrateHit"},
			hit_type = {"GQShoot","SectorShoot"},
			bullet_life_time = 6,
		},
		[17]=
		{
			id = 17,
			desc = "加特林一星普攻",
			speed = 20,
			bullet_num = 1,
			audio_name = "battle_snow",
			shouji_pre = "YX_JTL_zidan_shouji",
			bullet_prefab_name = "YX_JTL_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 6,
		},
		[18]=
		{
			id = 18,
			desc = "机枪炮技能",
			speed = 20,
			bullet_num = 1,
			damage = 50,
			audio_name = "battle_snow",
			shouji_pre = "xx_shouji",
			bullet_prefab_name = "jg_she_hongse",
			move = "LineCrossMove",
			hit_start = "HitLineCross",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "SectorShoot",
			bullet_life_time = 0.500000,
		},
		[19]=
		{
			id = 19,
			desc = "魔法球普通",
			speed = 20,
			bullet_num = 1,
			damage = 50,
			audio_name = "battle_snow",
			shouji_pre = "SD_hongse_shouji",
			bullet_prefab_name = "BulletPrefab_shandian",
			move = "LaserMove2",
			hit_start = "LaserHit",
			hit_effect = "LaserHit",
			hit_type = "SectorShoot",
			bullet_life_time = 0.500000,
		},
		[20]=
		{
			id = 20,
			desc = "魔法球技能",
			speed = {20,20,20,20,20},
			bullet_num = {1,1,1,1,1},
			damage = {20,20,20,20,20},
			audio_name = "battle_snow",
			shouji_pre = "xx_shouji",
			bullet_prefab_name = {"BulletPrefab_shandian_super","BulletPrefab_shandian_super","BulletPrefab_shandian_super","BulletPrefab_shandian_super","BulletPrefab_shandian_super"},
			move = {"LockMove","LockMove","LockMove","LockMove","LockMove"},
			hit_start = {"IsLockHit","IsLockHit","IsLockHit","IsLockHit","IsLockHit"},
			hit_effect = {"SampleHit","SampleHit","SampleHit","SampleHit","SampleHit"},
			hit_type = {"Lock","Lock","Lock","Lock","Lock"},
			bullet_life_time = 3,
		},
		[21]=
		{
			id = 21,
			desc = "火箭普攻",
			speed = 5,
			bullet_num = 1,
			damage = 50,
			audio_name = "battle_snow",
			shouji_pre = "baozha_xiao",
			bullet_prefab_name = "daodan_xiao_1",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "RocketBombHit",
			hit_type = "SectorShoot",
			bullet_life_time = 3,
		},
		[22]=
		{
			id = 22,
			desc = "瓶子炮",
			speed = 20,
			bullet_num = 1,
			audio_name = "battle_hero_huopao",
			shouji_pre = "YX_zidan_huo_shouji_02",
			bullet_prefab_name = "YX_zidna_pao_02",
			move = "DropGrenades",
			hit_start = "IsReachTarget",
			hit_effect = "BombHit#3",
			hit_type = "SectorShoot",
			bullet_life_time = 4,
		},
		[23]=
		{
			id = 23,
			desc = "瓶子炮",
			speed = 40,
			bullet_num = 6,
			audio_name = "battle_hero_huopao",
			shouji_pre = "YX_zidan_huo_shouji",
			bullet_prefab_name = "YX_zidna_huo",
			move = "LineMove",
			hit_start = "IsHitSomeOneOrIsReachTarget",
			hit_effect = "BombHit#3",
			hit_type = "SectorAndDartleShoot",
			bullet_life_time = 1,
		},
		[24]=
		{
			id = 24,
			speed = 15,
			bullet_num = 20,
			attr = "HitBack#100",
			audio_name = "battle_syringe",
			shouji_pre = "CS_jian_shouji_bao",
			bullet_prefab_name = "BulletPrefab6",
			move = "DropGrenades2",
			hit_start = "IsReachTarget",
			hit_effect = "SampleHit",
			hit_type = "DartleShoot#0.13",
			bullet_life_time = 2,
		},
		[25]=
		{
			id = 25,
			desc = "星星超级子弹",
			speed = 5,
			bullet_num = 1,
			damage = 50,
			attr = "Ice#100",
			hit_range = 8,
			audio_name = "battle_snow",
			shouji_pre = "xx_shouji",
			bullet_prefab_name = "B_bquan_skill",
			move = "BossWaveMove",
			hit_start = "HitOnSelfPos",
			hit_effect = "PenetrateBombHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[26]=
		{
			id = 26,
			desc = "弓箭超级子弹",
			speed = 6,
			bullet_num = 40,
			damage = 150,
			audio_name = "battle_arrow",
			shouji_pre = "Gj_shoji",
			bullet_prefab_name = "BulletPrefab4",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "CircleShoot",
			bullet_life_time = 6,
		},
		[27]=
		{
			id = 27,
			desc = "激光超级子弹",
			speed = 20,
			bullet_num = 1,
			damage = 100,
			audio_name = "battle_laser",
			shouji_pre = "Gj_shoji",
			bullet_prefab_name = "LaserPrefab1",
			move = "BigLaserMove",
			hit_start = "IsLockBigLaser",
			hit_effect = "BigLaserHit",
			hit_type = "Lock",
			bullet_life_time = 3,
		},
		[28]=
		{
			id = 28,
			desc = "毒液超级子弹",
			speed = 20,
			bullet_num = 1,
			damage = 50,
			attr = "Poisoning#5",
			audio_name = "battle_laser",
			shouji_pre = "duye_shouji",
			bullet_prefab_name = "BulletPrefab11",
			move = "SectorFireMove",
			hit_start = "IsSectorFire",
			hit_effect = "ExtraSampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 3,
		},
		[29]=
		{
			id = 29,
			desc = "星星普通子弹2个",
			speed = 20,
			bullet_num = 2,
			audio_name = "battle_snow",
			shouji_pre = "xx_shouji",
			bullet_prefab_name = "BulletPrefab7",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 5,
		},
		[30]=
		{
			id = 30,
			desc = "星星普通子弹2个（附带冰冻效果）",
			speed = 20,
			bullet_num = 2,
			attr = "Ice#20",
			audio_name = "battle_snow",
			shouji_pre = "xx_shouji",
			bullet_prefab_name = "BulletPrefab7",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 5,
		},
		[31]=
		{
			id = 31,
			desc = "星星普通子弹2个（附带冰冻效果）",
			speed = 20,
			bullet_num = 2,
			attr = "Ice#20",
			audio_name = "battle_snow",
			shouji_pre = "xx_shouji",
			bullet_prefab_name = "BulletPrefab7",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 5,
		},
		[32]=
		{
			id = 32,
			desc = "弓箭普通子弹2个",
			speed = 20,
			bullet_num = 5,
			audio_name = "battle_arrow",
			shouji_pre = "YX_zidna_jian_shouji_02",
			bullet_prefab_name = "BulletPrefab16",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[33]=
		{
			id = 33,
			desc = "弓箭普通子弹3个",
			speed = 20,
			bullet_num = 5,
			audio_name = "battle_arrow",
			shouji_pre = "YX_zidna_jian_shouji",
			bullet_prefab_name = "BulletPrefab4",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[34]=
		{
			id = 34,
			desc = "弓箭普通子弹4个",
			speed = 20,
			bullet_num = 5,
			audio_name = "battle_arrow",
			shouji_pre = "YX_zidna_jian_shouji",
			bullet_prefab_name = "BulletPrefab4",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[35]=
		{
			id = 35,
			desc = "瓶子跑普通子弹附加燃烧",
			speed = 20,
			bullet_num = 1,
			attr = "Firing#80#3",
			audio_name = "battle_hero_huopao",
			shouji_pre = "YX_zidan_huo_shouji",
			bullet_prefab_name = "YX_zidna_huo",
			move = "DropGrenades",
			hit_start = "IsReachTarget",
			hit_effect = "BombHit#3.6",
			hit_type = "DartleShoot#0.2",
			bullet_life_time = 10,
		},
		[36]=
		{
			id = 36,
			desc = "瓶子跑普通子弹附加燃烧（高级）",
			speed = 20,
			bullet_num = 1,
			attr = "Firing#130#3",
			audio_name = "battle_hero_huopao",
			shouji_pre = "YX_zidan_huo_shouji",
			bullet_prefab_name = "YX_zidna_huo",
			move = "DropGrenades",
			hit_start = "IsReachTarget",
			hit_effect = "BombHit#3.6",
			hit_type = "DartleShoot#0.2",
			bullet_life_time = 10,
		},
		[37]=
		{
			id = 37,
			desc = "瓶子跑普通子弹附加燃烧（高级，范围增加）",
			speed = 20,
			bullet_num = 1,
			attr = "Firing#130#3",
			audio_name = "battle_hero_huopao",
			shouji_pre = "YX_zidan_huo_shouji",
			bullet_prefab_name = "YX_zidna_huo_scale_16",
			move = "DropGrenades",
			hit_start = "IsReachTarget",
			hit_effect = "BombHit#4.8",
			hit_type = "DartleShoot#0.2",
			bullet_life_time = 10,
		},
		[38]=
		{
			id = 38,
			desc = "毒液普通子弹2个",
			speed = {20,20},
			bullet_num = {1,2},
			damage = {30,"#20"},
			attr = "Poisoning#40#3",
			audio_name = "battle_syringe",
			shouji_pre = "CS_jian_shouji_bao",
			bullet_prefab_name = {"BulletPrefab6","BulletPrefab14"},
			move = {"LineMove","LineMove"},
			hit_start = {"IsHitSomeOne","IsHitSomeOne"},
			hit_effect = {"SampleHit","SampleHit"},
			hit_type = {"SectorShoot","SectorShoot"},
			bullet_life_time = 2,
		},
		[39]=
		{
			id = 39,
			desc = "毒液普通子弹3个",
			speed = {20,20},
			bullet_num = {1,4},
			damage = {30,"#20"},
			attr = "Poisoning#40#3",
			audio_name = "battle_syringe",
			shouji_pre = "CS_jian_shouji_bao",
			bullet_prefab_name = {"BulletPrefab6","BulletPrefab14"},
			move = {"LineMove","LineMove"},
			hit_start = {"IsHitSomeOne","IsHitSomeOne"},
			hit_effect = {"SampleHit","SampleHit"},
			hit_type = {"SectorShoot","SectorShoot"},
			bullet_life_time = 2,
		},
		[40]=
		{
			id = 40,
			desc = "毒液普通子弹4个",
			speed = {20,20},
			bullet_num = {1,6},
			damage = {30,"#20"},
			attr = "Poisoning#55#5",
			audio_name = "battle_syringe",
			shouji_pre = "CS_jian_shouji_bao",
			bullet_prefab_name = {"BulletPrefab6","BulletPrefab14"},
			move = {"LineMove","LineMove"},
			hit_start = {"IsHitSomeOne","IsHitSomeOne"},
			hit_effect = {"SampleHit","SampleHit"},
			hit_type = {"SectorShoot","SectorShoot"},
			bullet_life_time = 2,
		},
		[41]=
		{
			id = 41,
			desc = "大炮一星",
			speed = 20,
			bullet_num = 1,
			damage = 0,
			audio_name = "battle_hero_dapao",
			bullet_prefab_name = "YX_dapao_zidan",
			move = "ReflectMove2",
			hit_start = "IsHitSome",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "SectorShoot",
			bullet_life_time = 6,
		},
		[42]=
		{
			id = 42,
			desc = "大炮二星",
			speed = {20,1},
			bullet_num = {1,1},
			damage = {0,"#666"},
			audio_name = "battle_hero_dapao",
			bullet_prefab_name = {"YX_dapao_zidan","YX_dapao_shouji"},
			move = {"ReflectMove2","DontMove"},
			hit_start = {"IsHitSome","IsTimeOver"},
			hit_effect = {"ExtraPenetrateHit","BombHit#3"},
			hit_type = {"SectorShoot","CircleShoot"},
			bullet_life_time = 6,
		},
		[43]=
		{
			id = 43,
			desc = "大炮三星",
			speed = {20,1},
			bullet_num = {1,1},
			damage = {0,"#666"},
			audio_name = "battle_hero_dapao",
			bullet_prefab_name = {"YX_dapao_zidan","YX_dapao_shouji_2"},
			move = {"ReflectMove2","DontMove"},
			hit_start = {"IsHitSome","IsTimeOver"},
			hit_effect = {"ExtraPenetrateHit","BombHit#6"},
			hit_type = {"SectorShoot","CircleShoot"},
			bullet_life_time = 6,
		},
		[44]=
		{
			id = 44,
			desc = "大炮四星",
			speed = {20,1},
			bullet_num = {1,1},
			damage = {0,"#999"},
			audio_name = "battle_hero_dapao",
			bullet_prefab_name = {"YX_dapao_zidan","YX_dapao_shouji_2"},
			move = {"ReflectMove2","DontMove"},
			hit_start = {"IsHitSome","IsTimeOver"},
			hit_effect = {"ExtraPenetrateHit","BombHit#6"},
			hit_type = {"SectorShoot","CircleShoot"},
			bullet_life_time = 6,
		},
		[45]=
		{
			id = 45,
			desc = "毒液普通子弹附加中毒",
			speed = 20,
			bullet_num = 1,
			attr = "Poisoning#100#3",
			audio_name = "battle_syringe",
			shouji_pre = "CS_jian_shouji_bao",
			bullet_prefab_name = "BulletPrefab6",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[46]=
		{
			id = 46,
			desc = "毒液普通子弹附加中毒",
			speed = 20,
			bullet_num = 1,
			attr = "Poisoning#100#3",
			audio_name = "battle_syringe",
			shouji_pre = "CS_jian_shouji_bao",
			bullet_prefab_name = "BulletPrefab6",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[47]=
		{
			id = 47,
			desc = "毒液普通子弹附加中毒（高级）",
			speed = 20,
			bullet_num = 1,
			attr = "Poisoning#126#5",
			audio_name = "battle_syringe",
			shouji_pre = "CS_jian_shouji_bao",
			bullet_prefab_name = "BulletPrefab6",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[48]=
		{
			id = 48,
			desc = "回旋镖二星",
			speed = 13,
			bullet_num = 1,
			audio_name = "battle_hero_feibiao",
			shouji_pre = "YX_zidan_hx_shouji_02",
			bullet_prefab_name = "YX_zidan_huixuan_02",
			move = "WhirlyMove",
			hit_start = "IsHitSome",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "SectorShoot",
			bullet_life_time = 30,
		},
		[49]=
		{
			id = 49,
			desc = "回旋镖三星",
			speed = 13,
			bullet_num = 1,
			audio_name = "battle_hero_feibiao",
			shouji_pre = "YX_zidan_hx_shouji_02",
			bullet_prefab_name = "YX_zidan_huixuan_03",
			move = "WhirlyMove",
			hit_start = "IsHitSome",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "SectorShoot",
			bullet_life_time = 30,
		},
		[50]=
		{
			id = 50,
			desc = "回旋镖四星",
			speed = 13,
			bullet_num = 1,
			audio_name = "battle_hero_feibiao",
			shouji_pre = "YX_zidan_hx_shouji_02",
			bullet_prefab_name = "YX_zidan_huixuan_03",
			move = "WhirlyMove",
			hit_start = "IsHitSome",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "SectorShoot",
			bullet_life_time = 30,
		},
		[51]=
		{
			id = 51,
			desc = "闪电球一星",
			speed = 1,
			bullet_num = 1,
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_ZD_skill_shouji",
			bullet_prefab_name = "YX_ZD_skill_Sdquan",
			move = "GQMoveWithSelf",
			hit_start = "IsHitSomeOnce",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "GQShoot",
			bullet_life_time = 1.300000,
		},
		[52]=
		{
			id = 52,
			desc = "闪电球二星",
			speed = 1,
			bullet_num = 1,
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_ZD_skill_shouji",
			bullet_prefab_name = "YX_ZD_skill_Sdquan_2",
			move = "GQMoveWithSelf",
			hit_start = "IsHitSomeOnce",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "GQShoot",
			bullet_life_time = 1.300000,
		},
		[53]=
		{
			id = 53,
			desc = "闪电球三星",
			speed = 1,
			bullet_num = 1,
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_ZD_skill_shouji",
			bullet_prefab_name = "YX_ZD_skill_Sdquan_2",
			move = "GQMoveWithSelf",
			hit_start = "IsHitSomeOnce",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "GQShoot",
			bullet_life_time = 1.300000,
		},
		[54]=
		{
			id = 54,
			desc = "闪电球四星",
			speed = 1,
			bullet_num = 1,
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_ZD_skill_shouji",
			bullet_prefab_name = "YX_ZD_skill_Sdquan_2",
			move = "GQMoveWithSelf",
			hit_start = "IsHitSomeOnce",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "GQShoot",
			bullet_life_time = 1.300000,
		},
		[55]=
		{
			id = 55,
			desc = "特斯拉一星",
			speed = 20,
			bullet_num = 1,
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_TSL_zidan_shouji_01",
			bullet_prefab_name = "YX_TSL_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[56]=
		{
			id = 56,
			desc = "特斯拉二星",
			speed = 20,
			bullet_num = 1,
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_TSL_zidan_shouji_01",
			bullet_prefab_name = "YX_TSL_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[57]=
		{
			id = 57,
			desc = "特斯拉三星",
			speed = 20,
			bullet_num = 1,
			attr = "Paralysis#20",
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_TSL_zidan_shouji_01",
			bullet_prefab_name = "YX_TSL_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[58]=
		{
			id = 58,
			desc = "特斯拉四星",
			speed = 20,
			bullet_num = 1,
			attr = "Paralysis#20",
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_TSL_zidan_shouji_01",
			bullet_prefab_name = "YX_TSL_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[59]=
		{
			id = 59,
			desc = "加特林二星普攻",
			speed = 20,
			bullet_num = 1,
			audio_name = "battle_snow",
			shouji_pre = "YX_JTL_zidan_shouji",
			bullet_prefab_name = "YX_JTL_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 6,
		},
		[60]=
		{
			id = 60,
			desc = "加特林三星普攻",
			speed = 20,
			bullet_num = 1,
			audio_name = "battle_snow",
			shouji_pre = "YX_JTL_zidan_shouji",
			bullet_prefab_name = "YX_JTL_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 6,
		},
		[61]=
		{
			id = 61,
			desc = "加特林四星普攻",
			speed = 20,
			bullet_num = 1,
			audio_name = "battle_snow",
			shouji_pre = "YX_JTL_zidan_shouji",
			bullet_prefab_name = "YX_JTL_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 6,
		},
		[62]=
		{
			id = 62,
			desc = "刺猬一星",
			speed = 1,
			bullet_num = 1,
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_ciwei_zidan_shouji",
			bullet_prefab_name = "ciwei_zidan",
			move = "GQMoveWithSelf",
			hit_start = "IsHitSomeOnce",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "GQShoot",
			bullet_life_time = 0.400000,
		},
		[63]=
		{
			id = 63,
			desc = "刺猬二星",
			speed = 1,
			bullet_num = 1,
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_ciwei_zidan_shouji",
			bullet_prefab_name = "ciwei_zidan_2",
			move = "GQMoveWithSelf",
			hit_start = "IsHitSomeOnce",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "GQShoot",
			bullet_life_time = 0.400000,
		},
		[64]=
		{
			id = 64,
			desc = "刺猬三星",
			speed = 1,
			bullet_num = 1,
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_ciwei_zidan_shouji",
			bullet_prefab_name = "ciwei_zidan_2",
			move = "GQMoveWithSelf",
			hit_start = "IsHitSomeOnce",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "GQShoot",
			bullet_life_time = 0.400000,
		},
		[65]=
		{
			id = 65,
			desc = "刺猬四星",
			speed = 1,
			bullet_num = 1,
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_ciwei_zidan_shouji",
			bullet_prefab_name = "ciwei_zidan_2",
			move = "GQMoveWithSelf",
			hit_start = "IsHitSomeOnce",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "GQShoot",
			bullet_life_time = 0.400000,
		},
		[66]=
		{
			id = 66,
			desc = "电锯一星",
			speed = 1,
			bullet_num = 1,
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_dianju_skill_shouji",
			bullet_prefab_name = "dianju_zidan",
			move = "GQMoveWithSelf",
			hit_start = "IsHitSomeOnce",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "GQShoot",
			bullet_life_time = 0.800000,
		},
		[67]=
		{
			id = 67,
			desc = "电锯二星",
			speed = 1,
			bullet_num = 1,
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_dianju_skill_shouji",
			bullet_prefab_name = "dianju_zidan_2",
			move = "GQMoveWithSelf",
			hit_start = "IsHitSomeOnce",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "GQShoot",
			bullet_life_time = 0.800000,
		},
		[68]=
		{
			id = 68,
			desc = "电锯三星",
			speed = 1,
			bullet_num = 1,
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_dianju_skill_shouji",
			bullet_prefab_name = "dianju_zidan_2",
			move = "GQMoveWithSelf",
			hit_start = "IsHitSomeOnce",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "GQShoot",
			bullet_life_time = 0.800000,
		},
		[69]=
		{
			id = 69,
			desc = "电锯四星",
			speed = 1,
			bullet_num = 1,
			audio_name = "battle_hero_shandian",
			shouji_pre = "YX_dianju_skill_shouji",
			bullet_prefab_name = "dianju_zidan_2",
			move = "GQMoveWithSelf",
			hit_start = "IsHitSomeOnce",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "GQShoot",
			bullet_life_time = 0.800000,
		},
		[70]=
		{
			id = 70,
			desc = "人间大炮一星",
			speed = 20,
			bullet_num = 1,
			attr = "Bursting#90#3",
			audio_name = "battle_syringe",
			shouji_pre = "YX_dapao_2ji_shouji",
			bullet_prefab_name = "YX_dapao_2ji_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[71]=
		{
			id = 71,
			desc = "人间大炮二星",
			speed = 20,
			bullet_num = 1,
			attr = "Bursting#135#3",
			audio_name = "battle_syringe",
			shouji_pre = "YX_dapao_2ji_shouji",
			bullet_prefab_name = "YX_dapao_2ji_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[72]=
		{
			id = 72,
			desc = "人间大炮三星",
			speed = 20,
			bullet_num = 1,
			attr = "Bursting#170#3",
			audio_name = "battle_syringe",
			shouji_pre = "YX_dapao_2ji_shouji",
			bullet_prefab_name = "YX_dapao_2ji_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[73]=
		{
			id = 73,
			desc = "人间大炮四星",
			speed = 20,
			bullet_num = 1,
			attr = "Bursting#190#5",
			audio_name = "battle_syringe",
			shouji_pre = "YX_dapao_2ji_shouji",
			bullet_prefab_name = "YX_dapao_2ji_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[74]=
		{
			id = 74,
			desc = "狂舞天使一星",
			speed = 20,
			bullet_num = 3,
			audio_name = "battle_arrow",
			shouji_pre = "YX_kwts_zidan_shouji",
			bullet_prefab_name = "YX_kwts_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[75]=
		{
			id = 75,
			desc = "狂舞天使二星",
			speed = 20,
			bullet_num = 5,
			audio_name = "battle_arrow",
			shouji_pre = "YX_kwts_zidan_shouji",
			bullet_prefab_name = "YX_kwts_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[76]=
		{
			id = 76,
			desc = "狂舞天使三星",
			speed = 20,
			bullet_num = 5,
			audio_name = "battle_arrow",
			shouji_pre = "YX_kwts_zidan_shouji",
			bullet_prefab_name = "YX_kwts_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[77]=
		{
			id = 77,
			desc = "狂舞天使四星",
			speed = 20,
			bullet_num = 5,
			audio_name = "battle_arrow",
			shouji_pre = "YX_kwts_zidan_shouji",
			bullet_prefab_name = "YX_kwts_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[78]=
		{
			id = 78,
			desc = "铁球1",
			speed = 20,
			bullet_num = 1,
			audio_name = "battle_snow",
			shouji_pre = "YX_TC_zidan_shouji",
			bullet_prefab_name = "YX_TC_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 5,
		},
		[79]=
		{
			id = 79,
			desc = "铁球2",
			speed = 20,
			bullet_num = 1,
			attr = "Dizziness#20",
			audio_name = "battle_snow",
			shouji_pre = "YX_TC_zidan_shouji",
			bullet_prefab_name = "YX_TC_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 5,
		},
		[80]=
		{
			id = 80,
			desc = "铁球3",
			speed = 20,
			bullet_num = 1,
			attr = "Dizziness#20",
			audio_name = "battle_snow",
			shouji_pre = "YX_TC_zidan_shouji",
			bullet_prefab_name = "YX_TC_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 5,
		},
		[81]=
		{
			id = 81,
			desc = "铁球4",
			speed = 20,
			bullet_num = 1,
			attr = "Dizziness#20",
			audio_name = "battle_snow",
			shouji_pre = "YX_TC_zidan_shouji",
			bullet_prefab_name = "YX_TC_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 5,
		},
		[82]=
		{
			id = 82,
			desc = "导弹英雄一星",
			speed = 20,
			bullet_num = 3,
			audio_name = "battle_arrow",
			shouji_pre = "YX_X_daodan_zidan_shouji",
			bullet_prefab_name = "YX_X_daodan_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[83]=
		{
			id = 83,
			desc = "导弹英雄二星",
			speed = 20,
			bullet_num = 5,
			audio_name = "battle_arrow",
			shouji_pre = "YX_X_daodan_zidan_shouji",
			bullet_prefab_name = "YX_X_daodan_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[84]=
		{
			id = 84,
			desc = "导弹英雄三星",
			speed = 20,
			bullet_num = 5,
			audio_name = "battle_arrow",
			shouji_pre = "YX_X_daodan_zidan_shouji",
			bullet_prefab_name = "YX_X_daodan_zidan",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
		[85]=
		{
			id = 85,
			desc = "导弹英雄四星",
			speed = 20,
			bullet_num = 5,
			audio_name = "battle_arrow",
			shouji_pre = "YX_X_daodan_zidan_shouji",
			bullet_prefab_name = "YX_X_daodan_zidan",
			move = "LineMove",
			hit_start = "IsHitSome",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
	},
}