return {
	base=
	{
		[1] = {
            type = 1,
			bullet_prefab_name = {"B_kuosan"},
			attackFrom = "hero",
			move = {"BossWaveMove"},
			hit_start = {"HitOnSelfPos"},
			hit_effect = {"PenetrateBombHit"},
			hit_type = {"SectorShoot"},
			speed = {5,},
			bullet_num = {1,},
			damage = {50,},
			bullet_life_time = 2,
			remark = "星星子弹2",
			shouji_pre = "xx_shouji",
			attr = {"Ice#100"},
			audio_name = "battle_snow",
        	hit_range = 8
        },
        [2] = {
            type = 2,
			bullet_prefab_name = {"BulletPrefab4"},
			attackFrom = "hero",
			move = {"LineMove"},
			hit_start = {"IsHitSomeOne"},
			hit_effect = {"SampleHit"},
			hit_type = {"CircleShoot"},
			speed = {6,},
			bullet_num = {40,},
			damage = {150,},
			bullet_life_time = 6,
			remark = "弓箭2",
			shouji_pre = "Gj_shoji",
			attr = {},
			audio_name = "battle_arrow",
        },
        [3] = {
            type = 3,
			bullet_prefab_name = {"LaserPrefab1"},
			attackFrom = "hero",
			move = {"BigLaserMove"},
			hit_start = {"IsLockBigLaser"},
			hit_effect = {"BigLaserHit"},
			hit_type = {"Lock"},
			speed = {20,},
			bullet_num = {1,},
			damage = {100,},
			bullet_life_time = 3,
			remark = "激光2",
			shouji_pre = "Gj_shoji",
			attr = {},
			audio_name = "battle_laser",
        },
        [4] = {
			type = 4,
			bullet_prefab_name = {"BulletPrefab11"},
			attackFrom = "hero",
			move = {"SectorFireMove"},
			hit_start = {"IsSectorFire"},
			hit_effect = {"ExtraSampleHit"},
			hit_type = {"SectorShoot"},
			speed = {20,},
			bullet_num = {1,},
			damage = {50,},
			bullet_life_time = 3,
			remark = "毒液",
			shouji_pre = "duye_shouji",
			attr = {"Poisoning#5"},
			audio_name = "battle_laser",
        },
	},
}