return 
{
	{
		name = "英雄",
		prefab = "HeroBase2D",
		cache_count = 20,
		isOnOff = 0,
	},
	{
		name = "飞的金币",
		prefab = "Monster_1_2D",
		cache_count = 50,
		isOnOff = 0,
	},
	{
		name = "飞的金币",
		prefab = "Monster_2_2D",
		cache_count = 50,
		isOnOff = 0,
	},
	{
		name = "飞的金币",
		prefab = "BulletPrefab6",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BulletPrefab7",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BulletPrefab8",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "B_kuosan",
		cache_count = 20,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BulletPrefab4",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BulletPrefab4",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "LaserPrefab1",
		cache_count = 20,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BulletPrefab11",
		cache_count = 20,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Gj_shoji",
		cache_count = 20,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Damage",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "xx_shouji",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "forzen",
		cache_count = 100,
		isOnOff = 1,
	},

	{
		name = "飞的金币",
		prefab = "Damage_Green",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "LaserPrefab2",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "duye_shouji",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "game_begin_fx",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Boss_coming_title",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BS_sg",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "HC_guangxiao_YX",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "FlyGlodPrefab",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Sj_shouji",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "SW_siwang",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BOOS_siwang",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Monster_1_2D_new_2d",
		cache_count = 100,
		isOnOff = 0,
	},
	{
		name = "飞的金币",
		prefab = "Monster_2_2D_new_2d",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Monster_Gold_2d",
		cache_count = 100,
		isOnOff = 0,
	},
	{
		name = "飞的金币",
		prefab = "Monster_4_2D_new_2d",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Monster_5_2D_2d",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Monster_6_2D_2d",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Monster_8_2D_2d",
		cache_count = 100,
		isOnOff = 0,
	},
	{
		name = "飞的金币",
		prefab = "Monster_7_2D_2d",
		cache_count = 100,
		isOnOff = 0,
	},
	{
		name = "飞的金币",
		prefab = "Monster_12_2D_new_2d",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Monster_Boss1_2d",
		cache_count = 1,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Monster_3_2d",
		cache_count = 100,
		isOnOff = 0,
	},
	{
		name = "飞的金币",
		prefab = "Monster_Boss2_2d",
		cache_count = 1,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Monster_Boss3_2d",
		cache_count = 1,
		isOnOff = 0,
	},
	{
		name = "飞的金币",
		prefab = "Monster_Boss_BaWangHua_2d",
		cache_count = 1,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Monster_Boss4_2d",
		cache_count = 1,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Monster_BossStoneFigure_2D",
		cache_count = 1,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BulletPrefab_boss1",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "CS_guaiwu_chuchang",
		cache_count = 20,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "men_hong",
		cache_count = 10,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "men_bai",
		cache_count = 10,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "target_indicator",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "YX_zidna_jian_shouji_02",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "YX_zidna_jian_shouji",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "YX_zidan_huo_shouji",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "ZY_jiantou_JT",
		cache_count = 10,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "SW_siwangt_yan",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "TW_jinbi",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "hero_egg",
		cache_count = 4,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "game_qyqk_fx",
		cache_count = 1,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "tb_chuxian_chuxian",
		cache_count = 4,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "tb_bao_xiaoshi",
		cache_count = 4,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "HC_guangxiao_YX_1",
		cache_count = 4,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "run_speed_up_icon",
		cache_count = 4,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "heal_speed_up_icon",
		cache_count = 4,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "hit_speed_up_icon",
		cache_count = 4,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "CSM_chuansongmen",
		cache_count = 2,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "CS_duye_shouji_01",
		cache_count = 20,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "YX_zidan_huo_shouji_02",
		cache_count = 20,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "GW_srh_baoza",
		cache_count = 20,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "GW_srh_zidan",
		cache_count = 20,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "gw_she_zidan_shouji",
		cache_count = 20,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BulletPrefab9",
		cache_count = 20,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BulletPrefab12",
		cache_count = 20,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "dufenhua_dufen",
		cache_count = 20,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BOOS_shouji_H",
		cache_count = 10,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BOOS_H_kuosan",
		cache_count = 10,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BulletCrabBoss",
		cache_count = 20,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BOOS_liusha_zadi",
		cache_count = 10,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BOOS_skill_xuanwo",
		cache_count = 10,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BulletPrefab_duhua_super",
		cache_count = 20,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "jg_she_hongse",
		cache_count = 10,
		isOnOff = 0,
	},
	{
		name = "飞的金币",
		prefab = "YX_zidna_huo_1",
		cache_count = 10,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "YX_zidna_huo_2",
		cache_count = 10,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BulletPrefab_shandian_1",
		cache_count = 10,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Damage_Heal",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Damage_Hero",
		cache_count = 100,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Damage_Green",
		cache_count = 10,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "Damage_Orange",
		cache_count = 10,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BOOS_juqi_daduan_1",
		cache_count = 2,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BOOS_juqi_daduan_2",
		cache_count = 2,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BOOS_juqi_daduan_3",
		cache_count = 2,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "BOOS_juqi_daduan_4",
		cache_count = 2,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "daduan_biankuang_UI_2",
		cache_count = 2,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "daduan_biankuang_UI_4",
		cache_count = 2,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "kuosan_anniu_quan_1",
		cache_count = 2,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "kuosan_anniu_quan_2",
		cache_count = 2,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "GoodsAddSkillTime",
		cache_count = 3,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "dj_sd_tb_dj_1",
		cache_count = 4,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "dj_sd_tb_dj_2",
		cache_count = 4,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "dj_sd_tb_dj_3",
		cache_count = 4,
		isOnOff = 1,
	},
	{
		name = "飞的金币",
		prefab = "C_bao_tubiao",
		cache_count = 2,
		isOnOff = 1,
	},
}