//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AStarWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AStar), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Create", Create);
		L.RegFunction("Destroy", Destroy);
		L.RegFunction("setGridSize", setGridSize);
		L.RegFunction("setMapSize", setMapSize);
		L.RegFunction("getCoordXByNo", getCoordXByNo);
		L.RegFunction("getCoordYByNo", getCoordYByNo);
		L.RegFunction("getNoByCoord", getNoByCoord);
		L.RegFunction("getCenterPointByNo", getCenterPointByNo);
		L.RegFunction("getCenterPointByXY", getCenterPointByXY);
		L.RegFunction("setNodeInf", setNodeInf);
		L.RegFunction("checkIsSafeByNo", checkIsSafeByNo);
		L.RegFunction("getPathByNo", getPathByNo);
		L.RegFunction("getPathNoByNo", getPathNoByNo);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Create(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			AStar obj = (AStar)ToLua.CheckObject<AStar>(L, 1);
			LuaInterface.PointTem arg0 = StackTraits<LuaInterface.PointTem>.Check(L, 2);
			LuaInterface.SizeTem arg1 = StackTraits<LuaInterface.SizeTem>.Check(L, 3);
			int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
			int arg3 = (int)LuaDLL.luaL_checknumber(L, 5);
			obj.Create(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Destroy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AStar obj = (AStar)ToLua.CheckObject<AStar>(L, 1);
			obj.Destroy();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setGridSize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AStar obj = (AStar)ToLua.CheckObject<AStar>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			obj.setGridSize(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setMapSize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AStar obj = (AStar)ToLua.CheckObject<AStar>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			obj.setMapSize(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getCoordXByNo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AStar obj = (AStar)ToLua.CheckObject<AStar>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int o = obj.getCoordXByNo(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getCoordYByNo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AStar obj = (AStar)ToLua.CheckObject<AStar>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int o = obj.getCoordYByNo(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getNoByCoord(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AStar obj = (AStar)ToLua.CheckObject<AStar>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			int o = obj.getNoByCoord(arg0, arg1);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getCenterPointByNo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AStar obj = (AStar)ToLua.CheckObject<AStar>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			LuaInterface.PointTem o = obj.getCenterPointByNo(arg0);
			ToLua.PushValue(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getCenterPointByXY(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AStar obj = (AStar)ToLua.CheckObject<AStar>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			LuaInterface.PointTem o = obj.getCenterPointByXY(arg0, arg1);
			ToLua.PushValue(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setNodeInf(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AStar obj = (AStar)ToLua.CheckObject<AStar>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			bool o = obj.setNodeInf(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int checkIsSafeByNo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AStar obj = (AStar)ToLua.CheckObject<AStar>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			bool o = obj.checkIsSafeByNo(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getPathByNo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AStar obj = (AStar)ToLua.CheckObject<AStar>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			LuaInterface.AStarPath o = obj.getPathByNo(arg0, arg1);
			ToLua.PushValue(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getPathNoByNo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AStar obj = (AStar)ToLua.CheckObject<AStar>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			LuaInterface.AStarPath o = obj.getPathNoByNo(arg0, arg1);
			ToLua.PushValue(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

