//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DataInfoWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DataInfo), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetDataInfo", GetDataInfo);
		L.RegFunction("GetDataInfoJson", GetDataInfoJson);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("infoList", get_infoList, set_infoList);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDataInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DataInfo obj = (DataInfo)ToLua.CheckObject<DataInfo>(L, 1);
			System.Collections.Generic.Dictionary<string,string> o = obj.GetDataInfo();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDataInfoJson(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DataInfo obj = (DataInfo)ToLua.CheckObject<DataInfo>(L, 1);
			string o = obj.GetDataInfoJson();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_infoList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DataInfo obj = (DataInfo)o;
			System.Collections.Generic.List<DataInfo.Info> ret = obj.infoList;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index infoList on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_infoList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DataInfo obj = (DataInfo)o;
			System.Collections.Generic.List<DataInfo.Info> arg0 = (System.Collections.Generic.List<DataInfo.Info>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<DataInfo.Info>));
			obj.infoList = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index infoList on a nil value");
		}
	}
}

