//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class InlineText_HrefClickEventWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(InlineText.HrefClickEvent), typeof(UnityEngine.Events.UnityEvent<string,int>));
		L.RegFunction("New", _CreateInlineText_HrefClickEvent);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateInlineText_HrefClickEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				InlineText.HrefClickEvent obj = new InlineText.HrefClickEvent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: InlineText.HrefClickEvent.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

