//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaInterface_AStarPathWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaInterface.AStarPath), null);
		L.RegFunction("New", _CreateLuaInterface_AStarPath);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("pathXY", get_pathXY, set_pathXY);
		L.RegVar("pathNo", get_pathNo, set_pathNo);
		L.RegVar("len", get_len, set_len);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLuaInterface_AStarPath(IntPtr L)
	{
		LuaInterface.AStarPath obj = new LuaInterface.AStarPath();
		ToLua.PushValue(L, obj);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_pathXY(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaInterface.AStarPath obj = (LuaInterface.AStarPath)o;
			LuaInterface.PointTem[] ret = obj.pathXY;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index pathXY on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_pathNo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaInterface.AStarPath obj = (LuaInterface.AStarPath)o;
			int[] ret = obj.pathNo;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index pathNo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_len(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaInterface.AStarPath obj = (LuaInterface.AStarPath)o;
			int ret = obj.len;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index len on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_pathXY(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaInterface.AStarPath obj = (LuaInterface.AStarPath)o;
			LuaInterface.PointTem[] arg0 = ToLua.CheckStructArray<LuaInterface.PointTem>(L, 2);
			obj.pathXY = arg0;
			ToLua.SetBack(L, 1, obj);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index pathXY on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_pathNo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaInterface.AStarPath obj = (LuaInterface.AStarPath)o;
			int[] arg0 = ToLua.CheckNumberArray<int>(L, 2);
			obj.pathNo = arg0;
			ToLua.SetBack(L, 1, obj);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index pathNo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_len(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaInterface.AStarPath obj = (LuaInterface.AStarPath)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.len = arg0;
			ToLua.SetBack(L, 1, obj);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index len on a nil value");
		}
	}
}

