//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Events_UnityEvent_string_intWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.Events.UnityEvent<string,int>), typeof(UnityEngine.Events.UnityEventBase), "UnityEvent_string_int");
		L.RegFunction("AddListener", AddListener);
		L.RegFunction("RemoveListener", RemoveListener);
		L.RegFunction("Invoke", Invoke);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Events.UnityEvent<string,int> obj = (UnityEngine.Events.UnityEvent<string,int>)ToLua.CheckObject<UnityEngine.Events.UnityEvent<string,int>>(L, 1);
			UnityEngine.Events.UnityAction<string,int> arg0 = (UnityEngine.Events.UnityAction<string,int>)ToLua.CheckDelegate<UnityEngine.Events.UnityAction<string,int>>(L, 2);
			obj.AddListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Events.UnityEvent<string,int> obj = (UnityEngine.Events.UnityEvent<string,int>)ToLua.CheckObject<UnityEngine.Events.UnityEvent<string,int>>(L, 1);
			UnityEngine.Events.UnityAction<string,int> arg0 = (UnityEngine.Events.UnityAction<string,int>)ToLua.CheckDelegate<UnityEngine.Events.UnityAction<string,int>>(L, 2);
			obj.RemoveListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Invoke(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Events.UnityEvent<string,int> obj = (UnityEngine.Events.UnityEvent<string,int>)ToLua.CheckObject<UnityEngine.Events.UnityEvent<string,int>>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			obj.Invoke(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

