//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Events_UnityEvent_PolygonClickWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.Events.UnityEvent<PolygonClick>), typeof(UnityEngine.Events.UnityEventBase), "UnityEvent_PolygonClick");
		L.RegFunction("AddListener", AddListener);
		L.RegFunction("RemoveListener", RemoveListener);
		L.RegFunction("Invoke", Invoke);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Events.UnityEvent<PolygonClick> obj = (UnityEngine.Events.UnityEvent<PolygonClick>)ToLua.CheckObject<UnityEngine.Events.UnityEvent<PolygonClick>>(L, 1);
			UnityEngine.Events.UnityAction<PolygonClick> arg0 = (UnityEngine.Events.UnityAction<PolygonClick>)ToLua.CheckDelegate<UnityEngine.Events.UnityAction<PolygonClick>>(L, 2);
			obj.AddListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Events.UnityEvent<PolygonClick> obj = (UnityEngine.Events.UnityEvent<PolygonClick>)ToLua.CheckObject<UnityEngine.Events.UnityEvent<PolygonClick>>(L, 1);
			UnityEngine.Events.UnityAction<PolygonClick> arg0 = (UnityEngine.Events.UnityAction<PolygonClick>)ToLua.CheckDelegate<UnityEngine.Events.UnityAction<PolygonClick>>(L, 2);
			obj.RemoveListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Invoke(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Events.UnityEvent<PolygonClick> obj = (UnityEngine.Events.UnityEvent<PolygonClick>)ToLua.CheckObject<UnityEngine.Events.UnityEvent<PolygonClick>>(L, 1);
			PolygonClick arg0 = (PolygonClick)ToLua.CheckObject<PolygonClick>(L, 2);
			obj.Invoke(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

