//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UniWebViewHelperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UniWebViewHelper), typeof(System.Object));
		L.RegFunction("StreamingAssetURLForPath", StreamingAssetURLForPath);
		L.RegFunction("PersistentDataURLForPath", PersistentDataURLForPath);
		L.RegFunction("New", _CreateUniWebViewHelper);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUniWebViewHelper(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UniWebViewHelper obj = new UniWebViewHelper();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UniWebViewHelper.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StreamingAssetURLForPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			string o = UniWebViewHelper.StreamingAssetURLForPath(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PersistentDataURLForPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			string o = UniWebViewHelper.PersistentDataURLForPath(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

